name: Terraform Plan

on:
  workflow_dispatch:
env:
  WORKING_DIR: 'example'

  ARM_CLIENT_ID : ${{ secrets.AZURE_CLIENT_ID }}

  ARM_CLIENT_SECRET : ${{ secrets.AZURE_CLIENT_SECRET }}

  ARM_SUBSCRIPTION_ID : ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  ARM_TENANT_ID : ${{ secrets.AZURE_TENANT_ID }}

  TF_VERSION: 1.4.6

  #VARS_FILE: dev.tfvars

jobs:  
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    #container:

    defaults:
      run:
        shell: bash
        working-directory: ./${{ env.WORKING_DIR }}

    steps:    
      - name: checkout
        uses: actions/checkout@v2


#       - name: Set Env

#         run: |

#           echo: "PLAN_FILE=${GITHUB_REF##*/}-dev.tfplan" >> $GITHUB_ENV

#           echo: "STATE_FILE=${GITHUB_REF##*/}.terraform.tfstate" >> GITHUB_ENV


      - name: login

        uses: azure/login@v1

        with:

            creds: ${{secrets.AZURE_CREDENTIALS}}

#           client-id: ${{ secrets.AZURE_CLIENT_ID }}

#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}

#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            enable-AzPSSession: true




      - name: terraform format

        id: fmt

        run: terraform fmt -recursive    


#       - name: terraform init

#         run: terraform init -backend-config=key=${env.STATE_FILE} -input=false 


      - name: 'Terraform Init'

        uses: hashicorp/terraform-github-actions@master

        with:

          tf_actions_version: 0.14.8

          tf_actions_subcommand: 'init'

          tf_actions_working_dir: "example"  


      - name: Run Azure PowerShell script

        uses: azure/powershell@v1

        with:

          inlineScript: |

            Get-AzContext   

          azPSVersion: "latest"  


      - name: 'Terraform Validate'

        uses: hashicorp/terraform-github-actions@master

        with:

          tf_actions_version: 0.14.8

          tf_actions_subcommand: 'validate'

          tf_actions_working_dir: "example"    



      - name: 'Terraform Plan'

        uses: hashicorp/terraform-github-actions@master

        with:

          tf_actions_version: 0.14.8

          tf_actions_subcommand: 'plan'

          tf_actions_working_dir: "example"   


      - name: Terraform Apply

        if: github.ref == 'refs/heads/main'

        uses: hashicorp/terraform-github-actions@master

        with:

          #creds: ${{secrets.AZURE_CREDENTIALS}}

          tf_actions_version: 0.14.8

          tf_actions_subcommand: 'apply'

          tf_actions_working_dir: "example"    


 
